# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verticadbs.vertica.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: verticadb-operator-webhook-service
          namespace: system
          path: /convert
      conversionReviewVersions:
      - v1beta1
